---
- name: MAIN - Create the Virtual Machine from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pwd }}"
    validate_certs: no
    port: "{{ vcenter_port }}"
    datacenter: "{{ vcenter_datacenter }}"
    esxi_hostname: "{{ esxi_hostname }}"
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    state: "{{ vm_state }}"
    guest_id: "{{ vm_guest_id }}"
    disk:
    - size_gb: "{{ vm_disk_size_gb }}"
      type: "{{ vm_disk_type }}"
      datastore: "{{ vm_disk_datastore }}"
    hardware:
      memory_mb: "{{ vm_ram_mb }}"
      num_cpus: "{{ vm_cpu }}"
      num_cpu_cores_per_socket: "{{ vm_cpu_cores_per_socket }}"
    networks:
    - name: "{{ ntw_name }}"
      ip: "{{ vm_ip }}"
      netmask: "{{ ntw_mask }}"
      gateway: "{{ ntw_gateway }}"
      dns_servers: "{{ ntw_dns_ips }}"
      domain: "{{ ntw_domain }}"
      wake_on_lan: "{{ ntw_wol }}"
      start_connected: "{{ ntw_connected }}"
    wait_for_ip_address: "{{ wait_for_vm_ip }}"
  register: create_vm

- debug:
    var: create_vm
    verbosity: 2